config/routes.rb
LunchMap::Application.routes.draw do
  resources :users
  resources :restaurants
  resources :sessions, only: [:new, :create, :destroy]

#以下に続くルートの通し方は、書き方が古い（今は使ってはいけない）らしいので、のちほど修正する
  root   "static_pages#home"
  get    "/signup"  => "users#new"
  get    "/signin"  => "sessions#new"
  delete "/signout" => "sessions#destroy"
  get    "/help"    => "static_pages#help"
  get    "/about"   => "static_pages#about"
  get    "/contact" => "static_pages#contact"

  get    "/signup2" => "restaurants#new"
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root "welcome#index"

  # Example of regular route:
  #   get "products/:id" => "catalog#view"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get "products/:id/purchase" => "catalog#purchase", as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get "short"
  #       post "toggle"
  #     end
  #
  #     collection do
  #       get "sold"
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get "recent", on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post "toggle"
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end

  def contact
  end

  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.jp/contact">contact page</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

  <h1>❀五反田ランチマップ❀</h1>


  <%= link_to "ログイン", signin_path, class: "btn btn-large btn-primary" %>
  <%= link_to "ユーザー新規登録", signup_path, class: "btn btn-large btn-primary" %>
  <br>

  <%= link_to "お店を見る", restaurants_path, class: "btn btn-large btn-primary" %>
  <%= link_to "お店を新規登録", signup2_path, class: "btn btn-large btn-primary" %>

</div>

<strong class="center">
  ↓↓登録店舗の位置情報↓↓
</center>
<div class="center" id="map_canvas" style="width:500px; height:300px"></center>